vich_uploader:
    db_driver: orm

    mappings:
       pictures_clients:
           uri_prefix: /images/pictures_clients
           upload_destination: '%kernel.project_dir%/public/images/pictures_clients'

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
