version : '2'

services: 
  
  netEscapedb:
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netEscape
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql-data/sql-scripts/:/docker-entrypoint-initdb.d/
    ports: 
      - "3306:3306"
    networks:
      - my-custom-network
      
  projectStack:
    build:
      context: .
      dockerfile: symfony4.dockerfile
    image: whatwedo/symfony4:v2.0
    ports: 
      - "80:80"
    networks:
      - my-custom-network

networks:
  my-custom-network:
    driver: bridge