<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container45zHfgH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container45zHfgH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container45zHfgH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container45zHfgH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container45zHfgH\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '45zHfgH',
    'container.build_id' => '371b3ef6',
    'container.build_time' => 1548256869,
), __DIR__.\DIRECTORY_SEPARATOR.'Container45zHfgH');
