<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPORNDlt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPORNDlt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPORNDlt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPORNDlt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPORNDlt\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'PORNDlt',
    'container.build_id' => '6c77c778',
    'container.build_time' => 1548324592,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPORNDlt');
