<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcNicAZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcNicAZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXcNicAZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXcNicAZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXcNicAZ\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'XcNicAZ',
    'container.build_id' => '4a64429b',
    'container.build_time' => 1548339464,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXcNicAZ');
