<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.LVd5Q4X' shared service.

return $this->privates['.service_locator.LVd5Q4X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'usersRepository' => array('privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService.php', true),
));
