<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.CLREBB2' shared service.

return $this->privates['.service_locator.CLREBB2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'user' => array('privates', '.errored..service_locator.CLREBB2.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.CLREBB2": it references class "App\\Entity\\Users" but no such service exists.'),
));
