<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yQ7UzAa' shared service.

return $this->privates['.service_locator.yQ7UzAa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'gamesRepository' => array('privates', 'App\\Repository\\GamesRepository', 'getGamesRepositoryService.php', true),
));
