<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, array(
    'App\\Controller\\GamesController::delete' => array('privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true),
    'App\\Controller\\GamesController::edit' => array('privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true),
    'App\\Controller\\GamesController::index' => array('privates', '.service_locator.yQ7UzAa', 'get_ServiceLocator_YQ7UzAaService.php', true),
    'App\\Controller\\GamesController::show' => array('privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true),
    'App\\Controller\\SecurityController::registration' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
    'App\\Controller\\UsersController::delete' => array('privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true),
    'App\\Controller\\UsersController::edit' => array('privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true),
    'App\\Controller\\UsersController::index' => array('privates', '.service_locator.LVd5Q4X', 'get_ServiceLocator_LVd5Q4XService.php', true),
    'App\\Controller\\UsersController::new' => array('privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true),
    'App\\Controller\\UsersController::show' => array('privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true),
    'App\\Controller\\GamesController:delete' => array('privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true),
    'App\\Controller\\GamesController:edit' => array('privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true),
    'App\\Controller\\GamesController:index' => array('privates', '.service_locator.yQ7UzAa', 'get_ServiceLocator_YQ7UzAaService.php', true),
    'App\\Controller\\GamesController:show' => array('privates', '.service_locator.dRIZDRu', 'get_ServiceLocator_DRIZDRuService.php', true),
    'App\\Controller\\SecurityController:registration' => array('privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true),
    'App\\Controller\\UsersController:delete' => array('privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true),
    'App\\Controller\\UsersController:edit' => array('privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true),
    'App\\Controller\\UsersController:index' => array('privates', '.service_locator.LVd5Q4X', 'get_ServiceLocator_LVd5Q4XService.php', true),
    'App\\Controller\\UsersController:new' => array('privates', '.service_locator._gPEhjd', 'get_ServiceLocator_GPEhjdService.php', true),
    'App\\Controller\\UsersController:show' => array('privates', '.service_locator.CLREBB2', 'get_ServiceLocator_CLREBB2Service.php', true),
))), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
